description: "Vefur fyrir birtingu laga Pírata."
email: "piratar@piratar.is"
github_username: "piratar"
plugins: ["jekyll-feed"]
repository: "https://github.com/piratar/log.piratar.is"
title: "Lög Pírata"
twitter_username: "piratarxp"
url: "https://log.piratar.is"